### ISSUE TITLE
AMD threads per core incorrectly hardcoded to 1

### ISSUE THREAD

**Issue by emaste** [NanXiao/lscpu#13]
Looking at https://www.amd.com/en/products/specifications/processors two threads per core is typical, but lscpu forces`threads_per_core` to 1 for AMD CPUs

https://github.com/NanXiao/lscpu/blob/master/lscpu.c#L805
```
    if (is_amd_cpu(x86_info->vendor))
    {
        /* AMD doesn't support Hyper-Threading */
        x86_info->threads_per_core = 1;
        x86_info->cores_per_socket = 1;
```

With Linux installed on a piece of test hardware, Linux lscpu reports
Thread(s) per core: 2
Core(s) per socket: 64
Socket(s): 2

On the same hardware with FreeBSD installed this lscpu reports
Thread(s) per core: 1
Core(s) per socket: 128
Socket(s): 2

**Comment by NanXiao** [comment]
@emaste @LaurentChardon just sent a PR and I have updated the code. When you have time, could you check whether the newest code fixes the issue (sorry, I don't have FreeBSD at hand), thanks very much!

**Comment by LaurentChardon** [comment]
I've improved it so it's more standard and works on all BSDs.

**Comment by NanXiao** [comment]
@LaurentChardon Thanks very much for your help! I will close this issue.
