### ISSUE TITLE
"Cannot allocate memory" on OpenBSD/i386  5.8

### ISSUE THREAD

**Issue by yggdr** [NanXiao/lscpu#3]
Output on OpenBSD/i386 5.8 on an PC Engines ALIX (AMD Geode processor):
    lscpu: HW_MODEL: Cannot allocate memory

cc is gcc version 4.2.1 20070719

While being an older OpenBSD version, this error surprised me. On an 6.1/amd64 VM it worked as expected.

**Comment by NanXiao** [comment]
Since I don't have `OpenBSD/i386` at hand, could you help to change [model](https://github.com/NanXiao/lscpu/blob/c2987e652ba7c5c87f5300651ef42b95ccf16c3f/lscpu.c#L32)'s buffer length from `64` to `128` to test? If it works, please tell me or your can send PR directly.  

Thanks very much in advance!

**Comment by yggdr** [comment]
That yields an
    lscpu: HW_VENDOR: Operation not supported

**Comment by NanXiao** [comment]
It should be `HW_VENDOR` is not supported  in `OpenBSD/i386 5.8`. Anyway, I will try to install a VM to test for it. Thanks very much for your report!

**Comment by yggdr** [comment]
FYI just installed a fresh OpenBSD 6.1 i386 on an PC Engines ALIX 2C3, same result.

**Comment by NanXiao** [comment]
Thanks for reporting, I will check it.

**Comment by NanXiao** [comment]
I update the [code](https://github.com/NanXiao/lscpu/commit/cf76c8bca9d295ee1ef8d67bd90af997d2abdb12), please try it, thanks very much!

**Comment by yggdr** [comment]
Seems to work in principle now, just seems to have difficulty detecting caches on AMD processors

Here is my workstation:

Architecture:            amd64
Byte Order:              Little Endian
Total CPU(s):            8
Vendor:                  AuthenticAMD
CPU family:              111
Model:                   2
Model name:              AMD FX-8370 Eight-Core Processor               
Stepping:                0
L1d cache:               0K
L1i cache:               0K
L2 cache:                0K
L3 cache:                0M
Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 cflsh mmx fxsr sse sse2 htt sse3 pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave osxsave avx f16c syscall mp fxsr_opt pdpe1gb lahf_lm cmp_legacy extapic osvw skinit wdt nodeid_msr perfctr_core dbx perftsc pcx_l2i

Here is the Alix box:

Architecture:            i386
Byte Order:              Little Endian
Active CPU(s):           1
Total CPU(s):            1
Vendor:                  AuthenticAMD
CPU family:              5
Model:                   10
Model name:              Geode(TM) Integrated Processor by AMD PCS ("AuthenticAMD" 586-class)
Stepping:                2
CPU MHz:                 499
L1d cache:               0K
L1i cache:               0K
L2 cache:                0K
L3 cache:                0M
Flags:                   fpu de pse tsc msr cx8 sep pge cmov cflsh mmx syscall mp

Thanks for the work :)

**Comment by NanXiao** [comment]
@yggdr Thanks very much for your report! I just update the code, and please try it again, thanks very much in advance!

**Comment by yggdr** [comment]
Now the cache detection seems to work :)
Although there are still less fields than in your Intel Xeon example in the README.md, e.g. Threads per Core and Cores per socket are missing.

Workstation:

Architecture:            amd64                                                                                                                                                                                                                                                                                                                                                                                                                                                                
Byte Order:              Little Endian
Total CPU(s):            8
Vendor:                  AuthenticAMD
CPU family:              111
Model:                   2
Model name:              AMD FX-8370 Eight-Core Processor               
Stepping:                0
L1d cache:               16K
L1i cache:               64K
L2 cache:                2048K
L3 cache:                8M
Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 cflsh mmx fxsr sse sse2 htt sse3 pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave osxsave avx f16c syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm lahf_lm cmp_legacy svm extapic cr8_legacy lzcnt sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb

Alix:

Architecture:            i386                              
Byte Order:              Little Endian                     
Active CPU(s):           1                                 
Total CPU(s):            1                                 
Vendor:                  AuthenticAMD                      
CPU family:              5                                 
Model:                   10                                
Model name:              Geode(TM) Integrated Processor by AMD PCS ("AuthenticAMD" 586-class)                          
Stepping:                2                                 
CPU MHz:                 499                               
L1d cache:               64K                               
L1i cache:               64K                               
L2 cache:                128K                              
L3 cache:                0M                                
Flags:                   fpu de pse tsc msr cx8 sep pge cmov cflsh mmx mmxext 3dnowext 3dnow

**Comment by NanXiao** [comment]
@yggdr Thanks for your great help! Yes, I haven't added `AMD` features for getting thread/core info, and try to add it ASAP.

**Comment by NanXiao** [comment]
@yggdr I have submitted the code of getting AMD thread/core info. If you have time, please try it, thanks very much for your great feedback and help!

**Comment by yggdr** [comment]
Alix:

Architecture:            i386
Byte Order:              Little Endian
Active CPU(s):           1
Total CPU(s):            1
Thread(s) per core:      1
Core(s) per socket:      1
Socket(s):               1
Vendor:                  AuthenticAMD
CPU family:              5
Model:                   10
Model name:              Geode(TM) Integrated Processor by AMD PCS ("AuthenticAMD" 586-class)
Stepping:                2
CPU MHz:                 499
L1d cache:               64K
L1i cache:               64K
L2 cache:                128K
L3 cache:                0K
Flags:                   fpu de pse tsc msr cx8 sep pge cmov cflsh mmx mmxext 3dnowext 3dnow

Workstation:

Architecture:            amd64
Byte Order:              Little Endian
Total CPU(s):            8
Thread(s) per core:      1
Core(s) per socket:      8
Socket(s):               0
Vendor:                  AuthenticAMD
CPU family:              111
Model:                   2
Model name:              AMD FX-8370 Eight-Core Processor               
Stepping:                0
L1d cache:               16K
L1i cache:               64K
L2 cache:                2048K
L3 cache:                8M
Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 cflsh mmx fxsr sse sse2 htt sse3 pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave osxsave avx f16c syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm lahf_lm cmp_legacy svm extapic cr8_legacy lzcnt sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb

It seems unable to get the active cpus, and on my workstation only the socket number and the frequency. No clue if the stepping is correct.
Thanks again :)

**Comment by NanXiao** [comment]
@yggdr I update the code. The stepping seems to be right, but the family is wrong. Thanks for your report. If you have time, please help me to test again, thanks very much for your time and help!

**Comment by yggdr** [comment]
Unfortunately commit 1a762967662846337836632d70510938dbc2f599 has broken the displaying of the CPU's caches.

Alix:

Architecture:            i386                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
Byte Order:              Little Endian                                                                                                                                                                                                                                                                                                                                                                                                                                                        
Active CPU(s):           1                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Total CPU(s):            1                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Thread(s) per core:      1                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Core(s) per socket:      1                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Socket(s):               1                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Vendor:                  AuthenticAMD                                                                                                                                                                                                                                                                                                                                                                                                                                                         
CPU family:              5                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
Model:                   10                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
Model name:              Geode(TM) Integrated Processor by AMD PCS ("AuthenticAMD" 586-class)                                                                                                                                                                                                                                                                                                                                                                                                 
Stepping:                2                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
CPU MHz:                 499                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
L3 cache:                0K                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
Flags:                   fpu de pse tsc msr cx8 sep pge cmov cflsh mmx mmxext 3dnowext 3dnow

Workstation:

Architecture:            amd64                                                                                         
Byte Order:              Little Endian                                                                                 
Total CPU(s):            8                                                                                             
Thread(s) per core:      1                                                                                             
Core(s) per socket:      8                                                                                             
Socket(s):               1                                                                                             
Vendor:                  AuthenticAMD                                                                                  
CPU family:              21                                                                                            
Model:                   2                                                                                             
Model name:              AMD FX-8370 Eight-Core Processor                                                              
Stepping:                0                                                                                             
Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 cflsh mmx fxsr sse sse2 htt sse3 pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave osxsave avx f16c syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm lahf_lm cmp_legacy svm extapic cr8_legacy lzcnt sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb

**Comment by NanXiao** [comment]
@yggdr I am very sorry my stupid error wasted your time. If possible, could you spare one minute to test it again? Thanks very much in advance! :-)

**Comment by yggdr** [comment]
No worries :) But still no frequency on my workstation

Alix

Architecture:            i386
Byte Order:              Little Endian
Active CPU(s):           1
Total CPU(s):            1
Thread(s) per core:      1
Core(s) per socket:      1
Socket(s):               1
Vendor:                  AuthenticAMD
CPU family:              5
Model:                   10
Model name:              Geode(TM) Integrated Processor by AMD PCS ("AuthenticAMD" 586-class)
Stepping:                2
CPU MHz:                 499
L1d cache:               64K
L1i cache:               64K
L2 cache:                128K
Flags:                   fpu de pse tsc msr cx8 sep pge cmov cflsh mmx mmxext 3dnowext 3dnow

Workstation

Architecture:            amd64
Byte Order:              Little Endian
Total CPU(s):            8
Thread(s) per core:      1
Core(s) per socket:      8
Socket(s):               1
Vendor:                  AuthenticAMD
CPU family:              21
Model:                   2
Model name:              AMD FX-8370 Eight-Core Processor               
Stepping:                0
L1d cache:               16K
L1i cache:               64K
L2 cache:                2048K
L3 cache:                8M
Flags:                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 cflsh mmx fxsr sse sse2 htt sse3 pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave osxsave avx f16c syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm lahf_lm cmp_legacy svm extapic cr8_legacy lzcnt sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb

**Comment by NanXiao** [comment]
@yggdr That's because the FreeBSD doesn't provide the `sysctl mob code` to obtain CPU speed(please refer [code](https://github.com/NanXiao/lscpu/blob/ef5441982893b572763555b363751148f816cf80/lscpu.c#L919)). I check the `CPUID` instruction, and find the speed can't be got directly. So I don't consider add this feature currently.  

Anyway, thanks very much for your time and help in the past week! I will close this issue, and when you have new feedback, please open a new issue.  

Best wishes & Thanks again!

**Comment by yggdr** [comment]
FreeBSD has the sysctls `dev.cpu.0.freq{,levels}`. Those might be useful if you ever implement this.
