### ISSUE TITLE
Please create a release

### ISSUE THREAD

**Issue by zi0r** [NanXiao/lscpu#4]
It doesn't matter if it is version 1.0 or version 0.0.1.  Please tag a release so port maintainers can easily add a port for your code.

**Comment by NanXiao** [comment]
@zi0r Thanks for your suggestion! I will consider to give a first release ASAP.

**Comment by NanXiao** [comment]
First release is done: [https://github.com/NanXiao/lscpu/releases/tag/1.0.0](https://github.com/NanXiao/lscpu/releases/tag/1.0.0). Thanks!
