### ISSUE TITLE
Add FreeBSD installation instructions

### ISSUE THREAD

**Issue by zi0r** [NanXiao/lscpu#5]
lscpu has been added to the FreeBSD ports tree:
[https://www.freshports.org/sysutils/lscpu](https://www.freshports.org/sysutils/lscpu)

To install the port: `cd /usr/ports/sysutils/lscpu/ && make install clean`
To add the package: `pkg install lscpu`

**Comment by NanXiao** [comment]
@zi0r Thanks very much for your work!
